

# Startup for Terraroute

version: '0.1.0'
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: terraroute-db
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  backend: 
    image: terraroute-backend:latest
    ports:
    - "8080:8080"
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: terraroute-db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  frontend:
    image: terraroute-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      APP_NAME: "terraRoute"
    depends_on:
      - backend

